const fs = require('fs');
let content = fs.readFileSync('lib/screens/pets/my_pets_screen.dart', 'utf8');

content = content.replace(
  "                    Row(children: [\n                      Expanded(\n                        child: OutlinedButton.icon(\n                          onPressed: () => Navigator.push(context,\n                            MaterialPageRoute(builder: (_) => EditPetScreen(petId: petId, pet: data))),\n                          icon: const Icon(Icons.edit_outlined, size: 16),\n                          label: const Text('Edit'),\n                          style: OutlinedButton.styleFrom(\n                            foregroundColor: AppTheme.primary,\n                            side: const BorderSide(color: AppTheme.primary),\n                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),\n                          ),\n                        ),\n                      ),\n                      const SizedBox(width: 12),\n                      Expanded(\n                        child: OutlinedButton.icon(\n                          onPressed: () => _confirmDelete(context, petId, data['name']),\n                          icon: const Icon(Icons.delete_outline, size: 16),\n                          label: const Text('Delete'),\n                          style: OutlinedButton.styleFrom(\n                            foregroundColor: Colors.red,\n                            side: const BorderSide(color: Colors.red),\n                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),\n                          ),\n                        ),\n                      ),\n                    ]),",
  "                    if (status != 'adopted') ...[                    \n                      ElevatedButton.icon(\n                        onPressed: () => _confirmAdopted(context, petId, data['name']),\n                        icon: const Icon(Icons.favorite, size: 16),\n                        label: const Text('Mark as Adopted'),\n                        style: ElevatedButton.styleFrom(\n                          backgroundColor: Colors.green,\n                          minimumSize: const Size(double.infinity, 42),\n                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),\n                        ),\n                      ),\n                      const SizedBox(height: 8),\n                    ],\n                    Row(children: [\n                      Expanded(\n                        child: OutlinedButton.icon(\n                          onPressed: () => Navigator.push(context,\n                            MaterialPageRoute(builder: (_) => EditPetScreen(petId: petId, pet: data))),\n                          icon: const Icon(Icons.edit_outlined, size: 16),\n                          label: const Text('Edit'),\n                          style: OutlinedButton.styleFrom(\n                            foregroundColor: AppTheme.primary,\n                            side: const BorderSide(color: AppTheme.primary),\n                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),\n                          ),\n                        ),\n                      ),\n                      const SizedBox(width: 12),\n                      Expanded(\n                        child: OutlinedButton.icon(\n                          onPressed: () => _confirmDelete(context, petId, data['name']),\n                          icon: const Icon(Icons.delete_outline, size: 16),\n                          label: const Text('Delete'),\n                          style: OutlinedButton.styleFrom(\n                            foregroundColor: Colors.red,\n                            side: const BorderSide(color: Colors.red),\n                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),\n                          ),\n                        ),\n                      ),\n                    ]),"
);

content = content.replace(
  "  void _confirmDelete(BuildContext context, String petId, String? name) {",
  "  void _confirmAdopted(BuildContext context, String petId, String? name) {\n    showDialog(\n      context: context,\n      builder: (_) => AlertDialog(\n        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),\n        title: const Row(children: [\n          Icon(Icons.favorite, color: Colors.green),\n          SizedBox(width: 8),\n          Text('Mark as Adopted'),\n        ]),\n        content: Text('\${name ?? 'This pet'} has found a home! Mark this listing as adopted?'),\n        actions: [\n          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),\n          ElevatedButton(\n            onPressed: () async {\n              Navigator.pop(context);\n              await FirebaseFirestore.instance.collection('pets').doc(petId).update({'status': 'adopted'});\n              if (context.mounted) {\n                ScaffoldMessenger.of(context).showSnackBar(\n                  SnackBar(content: Text('\${name ?? 'Pet'} has been marked as adopted!')));\n              }\n            },\n            style: ElevatedButton.styleFrom(backgroundColor: Colors.green),\n            child: const Text('Yes, Adopted!'),\n          ),\n        ],\n      ),\n    );\n  }\n\n  void _confirmDelete(BuildContext context, String petId, String? name) {"
);

fs.writeFileSync('lib/screens/pets/my_pets_screen.dart', content);
console.log('Done!');
