const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('Written: ' + filePath + ' (' + fs.statSync(filePath).size + ' bytes)');
}

write('lib/screens/auth/register_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:firebase_auth/firebase_auth.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/screens/home_screen.dart';",
"",
"class RegisterScreen extends StatefulWidget {",
"  const RegisterScreen({super.key});",
"  @override",
"  State<RegisterScreen> createState() => _RegisterScreenState();",
"}",
"class _RegisterScreenState extends State<RegisterScreen> {",
"  final _nameController = TextEditingController();",
"  final _emailController = TextEditingController();",
"  final _phoneController = TextEditingController();",
"  final _passwordController = TextEditingController();",
"  bool _isLoading = false;",
"  String? _errorMessage;",
"",
"  Future<void> _register() async {",
"    if (_nameController.text.isEmpty || _emailController.text.isEmpty || _passwordController.text.isEmpty) {",
"      setState(() => _errorMessage = 'Please fill in all required fields');",
"      return;",
"    }",
"    setState(() { _isLoading = true; _errorMessage = null; });",
"    try {",
"      final cred = await FirebaseAuth.instance.createUserWithEmailAndPassword(",
"        email: _emailController.text.trim(),",
"        password: _passwordController.text.trim(),",
"      );",
"      await FirebaseFirestore.instance.collection('users').doc(cred.user!.uid).set({",
"        'name': _nameController.text.trim(),",
"        'email': _emailController.text.trim(),",
"        'phone': _phoneController.text.trim(),",
"        'createdAt': FieldValue.serverTimestamp(),",
"      });",
"      if (!mounted) return;",
"      Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => HomeScreen()));",
"    } on FirebaseAuthException catch (e) {",
"      setState(() => _errorMessage = e.message);",
"    } finally {",
"      setState(() => _isLoading = false);",
"    }",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      backgroundColor: AppTheme.background,",
"      appBar: AppBar(title: const Text('Create Account')),",
"      body: SafeArea(",
"        child: SingleChildScrollView(",
"          padding: const EdgeInsets.all(24),",
"          child: Column(",
"            crossAxisAlignment: CrossAxisAlignment.start,",
"            children: [",
"              const SizedBox(height: 20),",
"              Center(child: Icon(Icons.pets, size: 64, color: AppTheme.primary)),",
"              const SizedBox(height: 16),",
"              const Center(child: Text('Join MauZanimo',",
"                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"              const SizedBox(height: 8),",
"              Center(child: Text('Create an account to start adopting',",
"                style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"              const SizedBox(height: 32),",
"              _field(_nameController, 'Full Name', Icons.person_outline),",
"              const SizedBox(height: 16),",
"              _field(_emailController, 'Email Address', Icons.email_outlined, keyboardType: TextInputType.emailAddress),",
"              const SizedBox(height: 16),",
"              _field(_phoneController, 'Phone Number', Icons.phone_outlined, keyboardType: TextInputType.phone),",
"              const SizedBox(height: 16),",
"              _field(_passwordController, 'Password', Icons.lock_outline, obscure: true),",
"              if (_errorMessage != null) ...[",
"                const SizedBox(height: 12),",
"                Text(_errorMessage!, style: const TextStyle(color: Colors.red, fontSize: 13)),",
"              ],",
"              const SizedBox(height: 24),",
"              SizedBox(",
"                width: double.infinity,",
"                child: ElevatedButton(",
"                  onPressed: _isLoading ? null : _register,",
"                  child: _isLoading",
"                    ? const CircularProgressIndicator(color: Colors.white)",
"                    : const Text('Create Account', style: TextStyle(fontSize: 16)),",
"                ),",
"              ),",
"              const SizedBox(height: 16),",
"              Center(",
"                child: GestureDetector(",
"                  onTap: () => Navigator.pop(context),",
"                  child: RichText(text: TextSpan(",
"                    text: 'Already have an account? ',",
"                    style: TextStyle(color: AppTheme.textDark.withOpacity(0.6)),",
"                    children: const [TextSpan(text: 'Sign In',",
"                      style: TextStyle(color: AppTheme.primary, fontWeight: FontWeight.bold))],",
"                  )),",
"                ),",
"              ),",
"            ],",
"          ),",
"        ),",
"      ),",
"    );",
"  }",
"",
"  Widget _field(TextEditingController c, String label, IconData icon,",
"    {TextInputType keyboardType = TextInputType.text, bool obscure = false}) =>",
"    TextField(controller: c, keyboardType: keyboardType, obscureText: obscure,",
"      decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon),",
"        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),",
"        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),",
"          borderSide: const BorderSide(color: AppTheme.primary, width: 2))));",
"}",
].join('\n'));
