const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('Written: ' + filePath + ' (' + fs.statSync(filePath).size + ' bytes)');
}

write('lib/screens/admin/admin_dashboard.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/screens/admin/add_pet_screen.dart';",
"import 'package:stray_pets_mu/screens/admin/inquiries_screen.dart';",
"",
"class AdminDashboard extends StatelessWidget {",
"  const AdminDashboard({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Admin Dashboard')),",
"      body: SingleChildScrollView(padding: const EdgeInsets.all(20), child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          const Text('Overview', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 16),",
"          Row(children: [",
"            Expanded(child: _StatCard(label: 'Total Pets', icon: Icons.pets, color: AppTheme.primary,",
"              stream: FirebaseFirestore.instance.collection('pets').snapshots())),",
"            const SizedBox(width: 12),",
"            Expanded(child: _StatCard(label: 'Inquiries', icon: Icons.mail_outline, color: AppTheme.accent,",
"              stream: FirebaseFirestore.instance.collection('inquiries').snapshots())),",
"          ]),",
"          const SizedBox(height: 12),",
"          Row(children: [",
"            Expanded(child: _StatCard(label: 'Adopted', icon: Icons.favorite, color: Colors.green,",
"              stream: FirebaseFirestore.instance.collection('pets').where('status', isEqualTo: 'adopted').snapshots())),",
"            const SizedBox(width: 12),",
"            Expanded(child: _StatCard(label: 'Pending', icon: Icons.hourglass_empty, color: Colors.orange,",
"              stream: FirebaseFirestore.instance.collection('inquiries').where('status', isEqualTo: 'pending').snapshots())),",
"          ]),",
"          const SizedBox(height: 32),",
"          const Text('Quick Actions', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 16),",
"          _Tile(icon: Icons.add_circle_outline, title: 'Add New Pet', subtitle: 'Register a new pet',",
"            onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AddPetScreen()))),",
"          const SizedBox(height: 12),",
"          _Tile(icon: Icons.inbox_outlined, title: 'View Inquiries', subtitle: 'Manage adoption inquiries',",
"            onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => InquiriesScreen()))),",
"        ],",
"      )),",
"    );",
"  }",
"}",
"class _StatCard extends StatelessWidget {",
"  final String label; final IconData icon; final Color color; final Stream<QuerySnapshot> stream;",
"  const _StatCard({required this.label, required this.icon, required this.color, required this.stream});",
"  @override",
"  Widget build(BuildContext context) => StreamBuilder<QuerySnapshot>(",
"    stream: stream,",
"    builder: (c, snap) => Container(",
"      padding: const EdgeInsets.all(16),",
"      decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(16)),",
"      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Icon(icon, color: color, size: 28), const SizedBox(height: 12),",
"        Text((snap.data?.docs.length ?? 0).toString(), style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: color)),",
"        Text(label, style: const TextStyle(fontSize: 13, color: AppTheme.textDark)),",
"      ]),",
"    ));",
"}",
"class _Tile extends StatelessWidget {",
"  final IconData icon; final String title, subtitle; final VoidCallback onTap;",
"  const _Tile({required this.icon, required this.title, required this.subtitle, required this.onTap});",
"  @override",
"  Widget build(BuildContext context) => GestureDetector(onTap: onTap, child: Container(",
"    padding: const EdgeInsets.all(16),",
"    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16),",
"      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.06), blurRadius: 10, offset: const Offset(0, 4))]),",
"    child: Row(children: [",
"      Container(padding: const EdgeInsets.all(10),",
"        decoration: BoxDecoration(color: AppTheme.primary.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),",
"        child: Icon(icon, color: AppTheme.primary)),",
"      const SizedBox(width: 16),",
"      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Text(title, style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"        Text(subtitle, style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"      ])),",
"      const Icon(Icons.arrow_forward_ios, size: 16, color: Colors.grey),",
"    ]),",
"  ));",
"}",
].join('\n'));

write('lib/screens/admin/add_pet_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class AddPetScreen extends StatefulWidget {",
"  const AddPetScreen({super.key});",
"  @override",
"  State<AddPetScreen> createState() => _AddPetScreenState();",
"}",
"class _AddPetScreenState extends State<AddPetScreen> {",
"  final _nameController = TextEditingController();",
"  final _locationController = TextEditingController();",
"  final _descriptionController = TextEditingController();",
"  final _imageUrlController = TextEditingController();",
"  final _ageController = TextEditingController();",
"  String _type = 'dogs'; String _gender = 'Male';",
"  bool _vaccinated = false; bool _sterilized = false; bool _isLoading = false;",
"  final _types = ['dogs', 'cats', 'others'];",
"  final _genders = ['Male', 'Female'];",
"",
"  Future<void> _save() async {",
"    if (_nameController.text.isEmpty || _locationController.text.isEmpty) {",
"      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill required fields')));",
"      return;",
"    }",
"    setState(() => _isLoading = true);",
"    try {",
"      await FirebaseFirestore.instance.collection('pets').add({",
"        'name': _nameController.text.trim(), 'type': _type,",
"        'location': _locationController.text.trim(),",
"        'description': _descriptionController.text.trim(),",
"        'imageUrl': _imageUrlController.text.trim(),",
"        'age': _ageController.text.trim(), 'gender': _gender,",
"        'vaccinated': _vaccinated, 'sterilized': _sterilized,",
"        'status': 'available', 'createdAt': FieldValue.serverTimestamp(),",
"      });",
"      if (!mounted) return;",
"      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Pet added!')));",
"      Navigator.pop(context);",
"    } catch (e) {",
"      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Something went wrong.')));",
"    } finally { setState(() => _isLoading = false); }",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) => Scaffold(",
"    appBar: AppBar(title: const Text('Add New Pet')),",
"    body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"      crossAxisAlignment: CrossAxisAlignment.start,",
"      children: [",
"        _f(_nameController, 'Pet Name', Icons.pets),",
"        const SizedBox(height: 16), _f(_ageController, 'Age', Icons.cake_outlined),",
"        const SizedBox(height: 16), _f(_locationController, 'Location', Icons.location_on_outlined),",
"        const SizedBox(height: 16), _f(_imageUrlController, 'Image URL', Icons.image_outlined),",
"        const SizedBox(height: 16), _f(_descriptionController, 'Description', Icons.description_outlined, maxLines: 4),",
"        const SizedBox(height: 16),",
"        const Text('Type', style: TextStyle(fontWeight: FontWeight.w500, color: AppTheme.textDark)),",
"        const SizedBox(height: 8),",
"        Row(children: _types.map((t) => GestureDetector(",
"          onTap: () => setState(() => _type = t),",
"          child: Container(margin: const EdgeInsets.only(right: 8),",
"            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),",
"            decoration: BoxDecoration(color: _type == t ? AppTheme.primary : AppTheme.lightGrey, borderRadius: BorderRadius.circular(20)),",
"            child: Text(t[0].toUpperCase() + t.substring(1),",
"              style: TextStyle(color: _type == t ? Colors.white : AppTheme.textDark, fontWeight: FontWeight.w500)))",
"        )).toList()),",
"        const SizedBox(height: 16),",
"        const Text('Gender', style: TextStyle(fontWeight: FontWeight.w500, color: AppTheme.textDark)),",
"        const SizedBox(height: 8),",
"        Row(children: _genders.map((g) => GestureDetector(",
"          onTap: () => setState(() => _gender = g),",
"          child: Container(margin: const EdgeInsets.only(right: 8),",
"            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),",
"            decoration: BoxDecoration(color: _gender == g ? AppTheme.primary : AppTheme.lightGrey, borderRadius: BorderRadius.circular(20)),",
"            child: Text(g, style: TextStyle(color: _gender == g ? Colors.white : AppTheme.textDark, fontWeight: FontWeight.w500)))",
"        )).toList()),",
"        SwitchListTile(title: const Text('Vaccinated'), value: _vaccinated, activeColor: AppTheme.primary, onChanged: (v) => setState(() => _vaccinated = v)),",
"        SwitchListTile(title: const Text('Sterilized'), value: _sterilized, activeColor: AppTheme.primary, onChanged: (v) => setState(() => _sterilized = v)),",
"        const SizedBox(height: 32),",
"        SizedBox(width: double.infinity, child: ElevatedButton(",
"          onPressed: _isLoading ? null : _save,",
"          child: _isLoading ? const CircularProgressIndicator(color: Colors.white) : const Text('Save Pet'))),",
"      ],",
"    )),",
"  );",
"  Widget _f(TextEditingController c, String label, IconData icon, {int maxLines = 1}) =>",
"    TextField(controller: c, maxLines: maxLines, decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon),",
"      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),",
"      focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),",
"        borderSide: const BorderSide(color: AppTheme.primary, width: 2))));",
"}",
].join('\n'));

write('lib/screens/admin/inquiries_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class InquiriesScreen extends StatelessWidget {",
"  const InquiriesScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) => Scaffold(",
"    appBar: AppBar(title: const Text('Adoption Inquiries')),",
"    body: StreamBuilder<QuerySnapshot>(",
"      stream: FirebaseFirestore.instance.collection('inquiries').orderBy('createdAt', descending: true).snapshots(),",
"      builder: (context, snapshot) {",
"        if (snapshot.connectionState == ConnectionState.waiting)",
"          return const Center(child: CircularProgressIndicator(color: AppTheme.primary));",
"        if (!snapshot.hasData || snapshot.data!.docs.isEmpty)",
"          return Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [",
"            Icon(Icons.inbox_outlined, size: 64, color: Colors.grey.shade300),",
"            const SizedBox(height: 16),",
"            const Text('No inquiries yet', style: TextStyle(color: Colors.grey)),",
"          ]));",
"        return ListView.builder(",
"          padding: const EdgeInsets.all(16),",
"          itemCount: snapshot.data!.docs.length,",
"          itemBuilder: (context, index) {",
"            final data = snapshot.data!.docs[index].data() as Map<String, dynamic>;",
"            final id = snapshot.data!.docs[index].id;",
"            return Container(",
"              margin: const EdgeInsets.only(bottom: 12), padding: const EdgeInsets.all(16),",
"              decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16),",
"                boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.06), blurRadius: 10, offset: const Offset(0, 4))]),",
"              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"                Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [",
"                  Text(data['applicantName'] ?? 'Unknown',",
"                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: AppTheme.textDark)),",
"                  _Badge(status: data['status'] ?? 'pending'),",
"                ]),",
"                const SizedBox(height: 6),",
"                Text('Pet: ' + (data['petName'] ?? 'Unknown'), style: const TextStyle(fontSize: 13, color: AppTheme.primary)),",
"                Text(data['email'] ?? '', style: const TextStyle(fontSize: 13, color: Colors.grey)),",
"                Text(data['phone'] ?? '', style: const TextStyle(fontSize: 13, color: Colors.grey)),",
"                const SizedBox(height: 12),",
"                Row(children: [",
"                  Expanded(child: OutlinedButton(",
"                    onPressed: () => _update(id, 'rejected'),",
"                    style: OutlinedButton.styleFrom(foregroundColor: Colors.red, side: const BorderSide(color: Colors.red),",
"                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8))),",
"                    child: const Text('Reject'))),",
"                  const SizedBox(width: 12),",
"                  Expanded(child: ElevatedButton(",
"                    onPressed: () => _update(id, 'approved'),",
"                    style: ElevatedButton.styleFrom(backgroundColor: Colors.green,",
"                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8))),",
"                    child: const Text('Approve'))),",
"                ]),",
"              ]),",
"            );",
"          });",
"      }),",
"  );",
"  Future<void> _update(String id, String status) =>",
"    FirebaseFirestore.instance.collection('inquiries').doc(id).update({'status': status});",
"}",
"class _Badge extends StatelessWidget {",
"  final String status;",
"  const _Badge({required this.status});",
"  @override",
"  Widget build(BuildContext context) {",
"    final color = status == 'approved' ? Colors.green : status == 'rejected' ? Colors.red : Colors.orange;",
"    return Container(",
"      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),",
"      decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(20)),",
"      child: Text(status[0].toUpperCase() + status.substring(1),",
"        style: TextStyle(fontSize: 11, color: color, fontWeight: FontWeight.w600)));",
"  }",
"}",
].join('\n'));
