const fs = require('fs');
const path = require('path');
fs.mkdirSync('lib/lang', { recursive: true });

fs.writeFileSync('lib/lang/app_strings.dart', [
"class AppStrings {",
"  static Map<String, Map<String, String>> translations = {",
"    'en': {",
"      'app_name': 'MauZanimo',",
"      'tagline': 'Find your perfect companion',",
"      'powered_by': 'Powered by JCI Grand Baie',",
"      'find_companion': 'Find a companion',",
"      'give_home': 'Give a stray pet a loving home',",
"      'search_pets': 'Search pets...',",
"      'all': 'All',",
"      'dogs': 'Dogs',",
"      'cats': 'Cats',",
"      'others': 'Others',",
"      'no_pets': 'No pets available yet',",
"      'list_pet': 'List a Pet',",
"      'saved_pets': 'Saved Pets',",
"      'no_saved': 'No saved pets yet',",
"      'no_saved_hint': 'Tap the heart on any pet to save them here.',",
"      'pets': 'Pets',",
"      'saved': 'Saved',",
"      'profile': 'Profile',",
"      'sign_in': 'Sign In',",
"      'sign_out': 'Sign Out',",
"      'sign_up': 'Sign Up',",
"      'email': 'Email',",
"      'password': 'Password',",
"      'forgot_password': 'Forgot Password?',",
"      'create_account': 'Create Account',",
"      'full_name': 'Full Name',",
"      'phone': 'Phone Number',",
"      'already_have_account': 'Already have an account?',",
"      'no_account': 'No account yet?',",
"      'about': 'About',",
"      'health_status': 'Health Status',",
"      'vaccinated': 'Vaccinated',",
"      'sterilized': 'Sterilized',",
"      'start_adoption': 'Start Adoption Process',",
"      'chat_whatsapp': 'Chat on WhatsApp',",
"      'adoption_inquiry': 'Adoption Inquiry',",
"      'your_details': 'Your Details',",
"      'submit_inquiry': 'Submit Inquiry',",
"      'inquiry_submitted': 'Inquiry Submitted!',",
"      'thank_you': 'Thank you for your interest.',",
"      'back_home': 'Back to Home',",
"      'donate': 'Donate to Us',",
"      'partners': 'Our Partners',",
"      'volunteer': 'Volunteer',",
"      'about_app': 'About MauZanimo',",
"      'contact': 'Contact Support',",
"      'lost_found': 'Lost & Found',",
"      'events': 'Adoption Events',",
"      'stories': 'Success Stories',",
"      'admin': 'Admin Dashboard',",
"      'language': 'Language',",
"    },",
"    'fr': {",
"      'app_name': 'MauZanimo',",
"      'tagline': 'Trouvez votre compagnon ideal',",
"      'powered_by': 'Propulse par JCI Grand Baie',",
"      'find_companion': 'Trouver un compagnon',",
"      'give_home': 'Donnez un foyer a un animal errant',",
"      'search_pets': 'Rechercher des animaux...',",
"      'all': 'Tous',",
"      'dogs': 'Chiens',",
"      'cats': 'Chats',",
"      'others': 'Autres',",
"      'no_pets': 'Aucun animal disponible',",
"      'list_pet': 'Ajouter un Animal',",
"      'saved_pets': 'Animaux Sauvegardes',",
"      'no_saved': 'Aucun animal sauvegarde',",
"      'no_saved_hint': 'Appuyez sur le coeur pour sauvegarder un animal.',",
"      'pets': 'Animaux',",
"      'saved': 'Sauvegardes',",
"      'profile': 'Profil',",
"      'sign_in': 'Se Connecter',",
"      'sign_out': 'Se Deconnecter',",
"      'sign_up': 'Inscription',",
"      'email': 'Email',",
"      'password': 'Mot de passe',",
"      'forgot_password': 'Mot de passe oublie?',",
"      'create_account': 'Creer un compte',",
"      'full_name': 'Nom complet',",
"      'phone': 'Numero de telephone',",
"      'already_have_account': 'Vous avez deja un compte?',",
"      'no_account': 'Pas encore de compte?',",
"      'about': 'A propos',",
"      'health_status': 'Etat de sante',",
"      'vaccinated': 'Vaccine',",
"      'sterilized': 'Sterilise',",
"      'start_adoption': 'Commencer adoption',",
"      'chat_whatsapp': 'Chatter sur WhatsApp',",
"      'adoption_inquiry': 'Demande adoption',",
"      'your_details': 'Vos informations',",
"      'submit_inquiry': 'Soumettre la demande',",
"      'inquiry_submitted': 'Demande soumise!',",
"      'thank_you': 'Merci pour votre interet.',",
"      'back_home': 'Retour accueil',",
"      'donate': 'Faire un don',",
"      'partners': 'Nos partenaires',",
"      'volunteer': 'Benevolat',",
"      'about_app': 'A propos de MauZanimo',",
"      'contact': 'Assistance',",
"      'lost_found': 'Perdu & Trouve',",
"      'events': 'Evenements adoption',",
"      'stories': 'Histoires de succes',",
"      'admin': 'Tableau de bord admin',",
"      'language': 'Langue',",
"    },",
"  };",
"",
"  static String get(String key, String lang) {",
"    return translations[lang]?[key] ?? translations['en']?[key] ?? key;",
"  }",
"}",
].join('\n'));

console.log('Done!');
