const fs = require('fs');
const path = require('path');
fs.mkdirSync('lib/screens', { recursive: true });

fs.writeFileSync('lib/screens/language_select_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:provider/provider.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/lang/language_provider.dart';",
"import 'package:stray_pets_mu/screens/onboarding_screen.dart';",
"",
"class LanguageSelectScreen extends StatelessWidget {",
"  const LanguageSelectScreen({super.key});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final langProvider = Provider.of<LanguageProvider>(context);",
"    return Scaffold(",
"      backgroundColor: const Color(0xFFFDF6EC),",
"      body: SafeArea(",
"        child: Padding(",
"          padding: const EdgeInsets.all(32),",
"          child: Column(",
"            mainAxisAlignment: MainAxisAlignment.center,",
"            children: [",
"              Image.asset('assets/images/jci_grand_baie.png', height: 100),",
"              const SizedBox(height: 32),",
"              const Icon(Icons.pets, size: 64, color: AppTheme.primary),",
"              const SizedBox(height: 16),",
"              const Text('MauZanimo',",
"                style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"              const SizedBox(height: 8),",
"              Text('Choose your language / Choisissez votre langue',",
"                textAlign: TextAlign.center,",
"                style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6))),",
"              const SizedBox(height: 48),",
"              _LangButton(",
"                flag: 'EN',",
"                label: 'English',",
"                sublabel: 'Continue in English',",
"                isSelected: langProvider.lang == 'en',",
"                onTap: () async {",
"                  if (langProvider.lang != 'en') await langProvider.toggleLanguage();",
"                  if (!context.mounted) return;",
"                  Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const OnboardingScreen()));",
"                },",
"              ),",
"              const SizedBox(height: 16),",
"              _LangButton(",
"                flag: 'FR',",
"                label: 'Francais',",
"                sublabel: 'Continuer en Francais',",
"                isSelected: langProvider.lang == 'fr',",
"                onTap: () async {",
"                  if (langProvider.lang != 'fr') await langProvider.toggleLanguage();",
"                  if (!context.mounted) return;",
"                  Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const OnboardingScreen()));",
"                },",
"              ),",
"            ],",
"          ),",
"        ),",
"      ),",
"    );",
"  }",
"}",
"",
"class _LangButton extends StatelessWidget {",
"  final String flag, label, sublabel;",
"  final bool isSelected;",
"  final VoidCallback onTap;",
"",
"  const _LangButton({",
"    required this.flag,",
"    required this.label,",
"    required this.sublabel,",
"    required this.isSelected,",
"    required this.onTap,",
"  });",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return GestureDetector(",
"      onTap: onTap,",
"      child: Container(",
"        width: double.infinity,",
"        padding: const EdgeInsets.all(20),",
"        decoration: BoxDecoration(",
"          color: isSelected ? AppTheme.primary : Colors.white,",
"          borderRadius: BorderRadius.circular(16),",
"          border: Border.all(color: isSelected ? AppTheme.primary : Colors.grey.shade200, width: 2),",
"          boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.06), blurRadius: 10, offset: const Offset(0, 4))],",
"        ),",
"        child: Row(children: [",
"          Container(",
"            width: 48, height: 48,",
"            decoration: BoxDecoration(",
"              color: isSelected ? Colors.white.withOpacity(0.2) : AppTheme.primary.withOpacity(0.1),",
"              borderRadius: BorderRadius.circular(12)),",
"            child: Center(child: Text(flag,",
"              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold,",
"                color: isSelected ? Colors.white : AppTheme.primary))),",
"          ),",
"          const SizedBox(width: 16),",
"          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"            Text(label, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold,",
"              color: isSelected ? Colors.white : AppTheme.textDark)),",
"            Text(sublabel, style: TextStyle(fontSize: 13,",
"              color: isSelected ? Colors.white.withOpacity(0.8) : Colors.grey)),",
"          ]),",
"          const Spacer(),",
"          Icon(isSelected ? Icons.check_circle : Icons.arrow_forward_ios,",
"            color: isSelected ? Colors.white : Colors.grey, size: isSelected ? 24 : 16),",
"        ]),",
"      ),",
"    );",
"  }",
"}",
].join('\n'));

console.log('Done!');
