const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('Written: ' + filePath + ' (' + fs.statSync(filePath).size + ' bytes)');
}

write('lib/screens/onboarding_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:shared_preferences/shared_preferences.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/screens/auth/login_screen.dart';",
"",
"class OnboardingScreen extends StatefulWidget {",
"  const OnboardingScreen({super.key});",
"  @override",
"  State<OnboardingScreen> createState() => _OnboardingScreenState();",
"}",
"",
"class _OnboardingScreenState extends State<OnboardingScreen> {",
"  final PageController _controller = PageController();",
"  int _currentPage = 0;",
"",
"  final List<Map<String, dynamic>> _pages = [",
"    {",
"      'icon': Icons.pets,",
"      'color': AppTheme.primary,",
"      'title': 'Welcome to MauZanimo',",
"      'subtitle': 'Connecting stray pets with loving homes across Mauritius.',",
"    },",
"    {",
"      'icon': Icons.search,",
"      'color': Colors.orange,",
"      'title': 'Find Your Companion',",
"      'subtitle': 'Browse dogs, cats and other pets looking for a forever home. Filter by type, age and location.',",
"    },",
"    {",
"      'icon': Icons.favorite_outline,",
"      'color': Colors.red,",
"      'title': 'Adopt with Confidence',",
"      'subtitle': 'Submit an adoption inquiry and our team will guide you through the process step by step.',",
"    },",
"    {",
"      'icon': Icons.volunteer_activism_outlined,",
"      'color': Colors.purple,",
"      'title': 'Be Part of the Change',",
"      'subtitle': 'List your pet, volunteer, donate or partner with us. Together we make Mauritius kinder for animals.',",
"    },",
"  ];",
"",
"  Future<void> _finish() async {",
"    final prefs = await SharedPreferences.getInstance();",
"    await prefs.setBool('onboarding_done', true);",
"    if (!mounted) return;",
"    Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => LoginScreen()));",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      backgroundColor: AppTheme.background,",
"      body: SafeArea(",
"        child: Column(",
"          children: [",
"            Align(",
"              alignment: Alignment.topRight,",
"              child: TextButton(",
"                onPressed: _finish,",
"                child: const Text('Skip', style: TextStyle(color: Colors.grey)),",
"              ),",
"            ),",
"            Expanded(",
"              child: PageView.builder(",
"                controller: _controller,",
"                onPageChanged: (index) => setState(() => _currentPage = index),",
"                itemCount: _pages.length,",
"                itemBuilder: (context, index) {",
"                  final page = _pages[index];",
"                  return Padding(",
"                    padding: const EdgeInsets.all(32),",
"                    child: Column(",
"                      mainAxisAlignment: MainAxisAlignment.center,",
"                      children: [",
"                        Container(",
"                          padding: const EdgeInsets.all(32),",
"                          decoration: BoxDecoration(",
"                            color: (page['color'] as Color).withOpacity(0.1),",
"                            shape: BoxShape.circle,",
"                          ),",
"                          child: Icon(page['icon'] as IconData, size: 80, color: page['color'] as Color),",
"                        ),",
"                        const SizedBox(height: 40),",
"                        Text(page['title'] as String,",
"                          textAlign: TextAlign.center,",
"                          style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"                        const SizedBox(height: 16),",
"                        Text(page['subtitle'] as String,",
"                          textAlign: TextAlign.center,",
"                          style: TextStyle(fontSize: 15, color: AppTheme.textDark.withOpacity(0.6), height: 1.6)),",
"                      ],",
"                    ),",
"                  );",
"                },",
"              ),",
"            ),",
"            Padding(",
"              padding: const EdgeInsets.all(24),",
"              child: Column(",
"                children: [",
"                  Row(",
"                    mainAxisAlignment: MainAxisAlignment.center,",
"                    children: List.generate(_pages.length, (index) => Container(",
"                      margin: const EdgeInsets.symmetric(horizontal: 4),",
"                      width: _currentPage == index ? 24 : 8,",
"                      height: 8,",
"                      decoration: BoxDecoration(",
"                        color: _currentPage == index ? AppTheme.primary : Colors.grey.shade300,",
"                        borderRadius: BorderRadius.circular(4),",
"                      ),",
"                    )),",
"                  ),",
"                  const SizedBox(height: 24),",
"                  SizedBox(",
"                    width: double.infinity,",
"                    child: ElevatedButton(",
"                      onPressed: () {",
"                        if (_currentPage < _pages.length - 1) {",
"                          _controller.nextPage(duration: const Duration(milliseconds: 300), curve: Curves.ease);",
"                        } else {",
"                          _finish();",
"                        }",
"                      },",
"                      child: Text(_currentPage < _pages.length - 1 ? 'Next' : 'Get Started',",
"                        style: const TextStyle(fontSize: 16)),",
"                    ),",
"                  ),",
"                ],",
"              ),",
"            ),",
"          ],",
"        ),",
"      ),",
"    );",
"  }",
"}",
].join('\n'));
