const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('Written: ' + filePath + ' (' + fs.statSync(filePath).size + ' bytes)');
}

write('lib/screens/stories/success_stories_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/screens/stories/add_story_screen.dart';",
"",
"class SuccessStoriesScreen extends StatelessWidget {",
"  const SuccessStoriesScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Success Stories')),",
"      floatingActionButton: FloatingActionButton.extended(",
"        onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AddStoryScreen())),",
"        backgroundColor: AppTheme.primary,",
"        icon: const Icon(Icons.add, color: Colors.white),",
"        label: const Text('Share Your Story', style: TextStyle(color: Colors.white)),",
"      ),",
"      body: StreamBuilder<QuerySnapshot>(",
"        stream: FirebaseFirestore.instance.collection('stories').orderBy('createdAt', descending: true).snapshots(),",
"        builder: (context, snapshot) {",
"          if (snapshot.connectionState == ConnectionState.waiting)",
"            return const Center(child: CircularProgressIndicator(color: AppTheme.primary));",
"          if (!snapshot.hasData || snapshot.data!.docs.isEmpty)",
"            return Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [",
"              Icon(Icons.auto_stories_outlined, size: 64, color: Colors.grey.shade300),",
"              const SizedBox(height: 16),",
"              const Text('No stories yet', style: TextStyle(color: Colors.grey, fontSize: 16)),",
"              const SizedBox(height: 8),",
"              const Text('Be the first to share your adoption story!', style: TextStyle(color: Colors.grey, fontSize: 13)),",
"            ]));",
"          return ListView.builder(",
"            padding: const EdgeInsets.fromLTRB(16, 16, 16, 100),",
"            itemCount: snapshot.data!.docs.length,",
"            itemBuilder: (context, index) {",
"              final data = snapshot.data!.docs[index].data() as Map<String, dynamic>;",
"              return Container(",
"                margin: const EdgeInsets.only(bottom: 16),",
"                decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16),",
"                  boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.06), blurRadius: 10, offset: const Offset(0, 4))]),",
"                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"                  if (data['imageUrl'] != null && data['imageUrl'].toString().isNotEmpty)",
"                    ClipRRect(",
"                      borderRadius: const BorderRadius.only(topLeft: Radius.circular(16), topRight: Radius.circular(16)),",
"                      child: Image.network(data['imageUrl'], height: 200, width: double.infinity, fit: BoxFit.cover,",
"                        errorBuilder: (c, e, s) => Container(height: 200, color: AppTheme.lightGrey,",
"                          child: const Center(child: Icon(Icons.pets, size: 48, color: AppTheme.primary)))),",
"                    ),",
"                  Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"                    Row(children: [",
"                      Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),",
"                        decoration: BoxDecoration(color: Colors.green.withOpacity(0.1), borderRadius: BorderRadius.circular(20)),",
"                        child: const Row(children: [",
"                          Icon(Icons.favorite, size: 12, color: Colors.green),",
"                          SizedBox(width: 4),",
"                          Text('Adopted', style: TextStyle(fontSize: 11, color: Colors.green, fontWeight: FontWeight.w600)),",
"                        ])),",
"                      const SizedBox(width: 8),",
"                      Text(data['petName'] ?? 'Unknown Pet',",
"                        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: AppTheme.textDark)),",
"                    ]),",
"                    const SizedBox(height: 8),",
"                    Text(data['story'] ?? '',",
"                      style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.7), height: 1.6)),",
"                    const SizedBox(height: 12),",
"                    Row(children: [",
"                      const Icon(Icons.person_outline, size: 14, color: Colors.grey),",
"                      const SizedBox(width: 4),",
"                      Text(data['adopterName'] ?? 'Anonymous', style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"                    ]),",
"                  ])),",
"                ]),",
"              );",
"            },",
"          );",
"        },",
"      ),",
"    );",
"  }",
"}",
].join('\n'));

write('lib/screens/stories/add_story_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:firebase_auth/firebase_auth.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class AddStoryScreen extends StatefulWidget {",
"  const AddStoryScreen({super.key});",
"  @override",
"  State<AddStoryScreen> createState() => _AddStoryScreenState();",
"}",
"class _AddStoryScreenState extends State<AddStoryScreen> {",
"  final _nameController = TextEditingController();",
"  final _petNameController = TextEditingController();",
"  final _storyController = TextEditingController();",
"  final _imageUrlController = TextEditingController();",
"  bool _isLoading = false;",
"  bool _submitted = false;",
"",
"  Future<void> _submit() async {",
"    if (_petNameController.text.isEmpty || _storyController.text.isEmpty) {",
"      ScaffoldMessenger.of(context).showSnackBar(",
"        const SnackBar(content: Text('Please fill in all required fields')));",
"      return;",
"    }",
"    setState(() => _isLoading = true);",
"    try {",
"      await FirebaseFirestore.instance.collection('stories').add({",
"        'petName': _petNameController.text.trim(),",
"        'adopterName': _nameController.text.trim(),",
"        'story': _storyController.text.trim(),",
"        'imageUrl': _imageUrlController.text.trim(),",
"        'userId': FirebaseAuth.instance.currentUser?.uid,",
"        'createdAt': FieldValue.serverTimestamp(),",
"      });",
"      setState(() => _submitted = true);",
"    } catch (e) {",
"      ScaffoldMessenger.of(context).showSnackBar(",
"        const SnackBar(content: Text('Something went wrong. Please try again.')));",
"    } finally {",
"      setState(() => _isLoading = false);",
"    }",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Share Your Story')),",
"      body: _submitted ? _success() : _form(),",
"    );",
"  }",
"",
"  Widget _success() => Center(child: Padding(padding: const EdgeInsets.all(32), child: Column(",
"    mainAxisAlignment: MainAxisAlignment.center,",
"    children: [",
"      const Icon(Icons.favorite, size: 100, color: Colors.red),",
"      const SizedBox(height: 24),",
"      const Text('Story Shared!', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"      const SizedBox(height: 12),",
"      const Text('Thank you for sharing your adoption story. You are inspiring others to adopt!',",
"        textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Colors.grey, height: 1.6)),",
"      const SizedBox(height: 32),",
"      ElevatedButton(onPressed: () => Navigator.pop(context), child: const Text('Go Back')),",
"    ])));",
"",
"  Widget _form() => SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"    crossAxisAlignment: CrossAxisAlignment.start,",
"    children: [",
"      Container(padding: const EdgeInsets.all(16),",
"        decoration: BoxDecoration(color: Colors.green.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),",
"        child: const Row(children: [",
"          Icon(Icons.favorite, color: Colors.green),",
"          SizedBox(width: 12),",
"          Expanded(child: Text('Share your adoption story and inspire others to give a pet a loving home.',",
"            style: TextStyle(fontSize: 13, color: AppTheme.textDark))),",
"        ])),",
"      const SizedBox(height: 24),",
"      _f(_nameController, 'Your Name (optional)', Icons.person_outline),",
"      const SizedBox(height: 16),",
"      _f(_petNameController, 'Pet Name', Icons.pets),",
"      const SizedBox(height: 16),",
"      _f(_imageUrlController, 'Photo URL (optional)', Icons.image_outlined),",
"      const SizedBox(height: 16),",
"      _f(_storyController, 'Tell us your story...', Icons.auto_stories_outlined, maxLines: 6),",
"      const SizedBox(height: 32),",
"      SizedBox(width: double.infinity, child: ElevatedButton(",
"        onPressed: _isLoading ? null : _submit,",
"        child: _isLoading ? const CircularProgressIndicator(color: Colors.white) : const Text('Share Story', style: TextStyle(fontSize: 16)))),",
"    ]));",
"",
"  Widget _f(TextEditingController c, String label, IconData icon, {int maxLines = 1}) =>",
"    TextField(controller: c, maxLines: maxLines,",
"      decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon),",
"        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),",
"        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),",
"          borderSide: const BorderSide(color: AppTheme.primary, width: 2))));",
"}",
].join('\n'));
