const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('Written: ' + filePath + ' (' + fs.statSync(filePath).size + ' bytes)');
}

write('lib/screens/drawer_menu.dart', [
"import 'package:flutter/material.dart';",
"import 'package:firebase_auth/firebase_auth.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"import 'package:stray_pets_mu/screens/auth/login_screen.dart';",
"import 'package:stray_pets_mu/screens/info/donate_screen.dart';",
"import 'package:stray_pets_mu/screens/info/partners_screen.dart';",
"import 'package:stray_pets_mu/screens/info/contact_screen.dart';",
"import 'package:stray_pets_mu/screens/info/about_screen.dart';",
"import 'package:stray_pets_mu/screens/info/volunteer_screen.dart';",
"",
"class AppDrawer extends StatelessWidget {",
"  const AppDrawer({super.key});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final user = FirebaseAuth.instance.currentUser;",
"    return Drawer(",
"      child: Column(",
"        children: [",
"          Container(",
"            width: double.infinity,",
"            padding: const EdgeInsets.fromLTRB(20, 60, 20, 24),",
"            decoration: const BoxDecoration(color: AppTheme.primary),",
"            child: Column(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                Image.asset('assets/images/jci_grand_baie.png', height: 60),",
"                const SizedBox(height: 16),",
"                const Text('MauZanimo',",
"                  style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: Colors.white)),",
"                const SizedBox(height: 4),",
"                Text(user?.email ?? 'Guest',",
"                  style: TextStyle(fontSize: 13, color: Colors.white.withOpacity(0.8))),",
"              ],",
"            ),",
"          ),",
"          Expanded(",
"            child: ListView(",
"              padding: EdgeInsets.zero,",
"              children: [",
"                const SizedBox(height: 8),",
"                _DrawerTile(",
"                  icon: Icons.favorite_outline,",
"                  title: 'Donate to Us',",
"                  subtitle: 'Support our mission',",
"                  color: Colors.red,",
"                  onTap: () { Navigator.pop(context); Navigator.push(context, MaterialPageRoute(builder: (_) => DonateScreen())); },",
"                ),",
"                _DrawerTile(",
"                  icon: Icons.handshake_outlined,",
"                  title: 'Our Partners',",
"                  subtitle: 'Vets, shelters and NGOs',",
"                  color: AppTheme.primary,",
"                  onTap: () { Navigator.pop(context); Navigator.push(context, MaterialPageRoute(builder: (_) => PartnersScreen())); },",
"                ),",
"                _DrawerTile(",
"                  icon: Icons.volunteer_activism_outlined,",
"                  title: 'Volunteer',",
"                  subtitle: 'Join our community',",
"                  color: Colors.orange,",
"                  onTap: () { Navigator.pop(context); Navigator.push(context, MaterialPageRoute(builder: (_) => VolunteerScreen())); },",
"                ),",
"                _DrawerTile(",
"                  icon: Icons.info_outline,",
"                  title: 'About MauZanimo',",
"                  subtitle: 'Our story and mission',",
"                  color: Colors.blue,",
"                  onTap: () { Navigator.pop(context); Navigator.push(context, MaterialPageRoute(builder: (_) => AboutScreen())); },",
"                ),",
"                _DrawerTile(",
"                  icon: Icons.support_agent_outlined,",
"                  title: 'Contact Support',",
"                  subtitle: 'Get help from our team',",
"                  color: Colors.purple,",
"                  onTap: () { Navigator.pop(context); Navigator.push(context, MaterialPageRoute(builder: (_) => ContactScreen())); },",
"                ),",
"                const Divider(height: 32),",
"                _DrawerTile(",
"                  icon: Icons.logout,",
"                  title: 'Sign Out',",
"                  subtitle: '',",
"                  color: Colors.grey,",
"                  onTap: () async {",
"                    await FirebaseAuth.instance.signOut();",
"                    if (!context.mounted) return;",
"                    Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => LoginScreen()));",
"                  },",
"                ),",
"              ],",
"            ),",
"          ),",
"          Padding(",
"            padding: const EdgeInsets.all(16),",
"            child: Text('Powered by JCI Grand Baie',",
"              style: TextStyle(fontSize: 11, color: Colors.grey.shade400)),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"class _DrawerTile extends StatelessWidget {",
"  final IconData icon;",
"  final String title;",
"  final String subtitle;",
"  final Color color;",
"  final VoidCallback onTap;",
"",
"  const _DrawerTile({",
"    required this.icon,",
"    required this.title,",
"    required this.subtitle,",
"    required this.color,",
"    required this.onTap,",
"  });",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return ListTile(",
"      leading: Container(",
"        padding: const EdgeInsets.all(8),",
"        decoration: BoxDecoration(",
"          color: color.withOpacity(0.1),",
"          borderRadius: BorderRadius.circular(10),",
"        ),",
"        child: Icon(icon, color: color, size: 22),",
"      ),",
"      title: Text(title, style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14, color: AppTheme.textDark)),",
"      subtitle: subtitle.isNotEmpty ? Text(subtitle, style: const TextStyle(fontSize: 11, color: Colors.grey)) : null,",
"      trailing: const Icon(Icons.arrow_forward_ios, size: 14, color: Colors.grey),",
"      onTap: onTap,",
"    );",
"  }",
"}",
].join('\n'));

write('lib/screens/info/donate_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class DonateScreen extends StatelessWidget {",
"  const DonateScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Donate to Us')),",
"      body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          Center(child: Icon(Icons.favorite, size: 80, color: Colors.red.shade400)),",
"          const SizedBox(height: 16),",
"          const Center(child: Text('Support MauZanimo',",
"            style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"          const SizedBox(height: 8),",
"          Center(child: Text('Your donation helps stray pets find loving homes',",
"            textAlign: TextAlign.center,",
"            style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"          const SizedBox(height: 32),",
"          _InfoCard(icon: Icons.medical_services_outlined, color: Colors.red,",
"            title: 'Veterinary Care', description: 'Help cover medical costs for rescued animals'),",
"          const SizedBox(height: 12),",
"          _InfoCard(icon: Icons.home_outlined, color: Colors.orange,",
"            title: 'Shelter Support', description: 'Fund shelter operations and animal care'),",
"          const SizedBox(height: 12),",
"          _InfoCard(icon: Icons.campaign_outlined, color: AppTheme.primary,",
"            title: 'Awareness Campaigns', description: 'Spread the word about responsible pet ownership'),",
"          const SizedBox(height: 32),",
"          const Text('Bank Transfer Details',",
"            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 12),",
"          Container(padding: const EdgeInsets.all(16),",
"            decoration: BoxDecoration(color: AppTheme.lightGrey, borderRadius: BorderRadius.circular(12)),",
"            child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"              Text('Bank: MCB Mauritius', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"              SizedBox(height: 6),",
"              Text('Account Name: JCI Grand Baie', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"              SizedBox(height: 6),",
"              Text('Account No: XXXX-XXXX-XXXX', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"              SizedBox(height: 6),",
"              Text('Reference: MauZanimo Donation', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"            ]),",
"          ),",
"          const SizedBox(height: 24),",
"          SizedBox(width: double.infinity, child: ElevatedButton.icon(",
"            onPressed: () {},",
"            icon: const Icon(Icons.email_outlined),",
"            label: const Text('Contact Us for Other Payment Methods'))),",
"        ],",
"      )),",
"    );",
"  }",
"}",
"",
"class _InfoCard extends StatelessWidget {",
"  final IconData icon; final Color color; final String title, description;",
"  const _InfoCard({required this.icon, required this.color, required this.title, required this.description});",
"  @override",
"  Widget build(BuildContext context) => Container(",
"    padding: const EdgeInsets.all(16),",
"    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
"      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 8, offset: const Offset(0, 2))]),",
"    child: Row(children: [",
"      Container(padding: const EdgeInsets.all(10),",
"        decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(10)),",
"        child: Icon(icon, color: color)),",
"      const SizedBox(width: 16),",
"      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Text(title, style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"        const SizedBox(height: 4),",
"        Text(description, style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"      ])),",
"    ]),",
"  );",
"}",
].join('\n'));

write('lib/screens/info/partners_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class PartnersScreen extends StatelessWidget {",
"  const PartnersScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Our Partners')),",
"      body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          Center(child: Icon(Icons.handshake_outlined, size: 80, color: AppTheme.primary)),",
"          const SizedBox(height: 16),",
"          const Center(child: Text('Our Partners',",
"            style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"          const SizedBox(height: 8),",
"          Center(child: Text('Working together for animal welfare in Mauritius',",
"            textAlign: TextAlign.center,",
"            style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"          const SizedBox(height: 32),",
"          const Text('Veterinary Clinics', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 12),",
"          _PartnerCard(name: 'Grand Baie Vet Clinic', type: 'Veterinary', location: 'Grand Baie', icon: Icons.medical_services_outlined, color: Colors.blue),",
"          const SizedBox(height: 8),",
"          _PartnerCard(name: 'Pamplemousses Animal Hospital', type: 'Veterinary', location: 'Pamplemousses', icon: Icons.local_hospital_outlined, color: Colors.red),",
"          const SizedBox(height: 24),",
"          const Text('Animal Shelters', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 12),",
"          _PartnerCard(name: 'MSPCA Mauritius', type: 'Shelter', location: 'Port Louis', icon: Icons.home_outlined, color: Colors.orange),",
"          const SizedBox(height: 8),",
"          _PartnerCard(name: 'Animal Rescue Mauritius', type: 'NGO', location: 'Nationwide', icon: Icons.volunteer_activism_outlined, color: Colors.green),",
"          const SizedBox(height: 32),",
"          Container(padding: const EdgeInsets.all(16),",
"            decoration: BoxDecoration(color: AppTheme.primary.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),",
"            child: Row(children: [",
"              const Icon(Icons.add_business_outlined, color: AppTheme.primary),",
"              const SizedBox(width: 12),",
"              const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"                Text('Become a Partner', style: TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"                Text('Contact us to join our network', style: TextStyle(fontSize: 12, color: Colors.grey)),",
"              ])),",
"            ])),",
"          ),",
"        ],",
"      )),",
"    );",
"  }",
"}",
"",
"class _PartnerCard extends StatelessWidget {",
"  final String name, type, location; final IconData icon; final Color color;",
"  const _PartnerCard({required this.name, required this.type, required this.location, required this.icon, required this.color});",
"  @override",
"  Widget build(BuildContext context) => Container(",
"    padding: const EdgeInsets.all(16),",
"    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
"      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 8, offset: const Offset(0, 2))]),",
"    child: Row(children: [",
"      Container(padding: const EdgeInsets.all(10),",
"        decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(10)),",
"        child: Icon(icon, color: color)),",
"      const SizedBox(width: 16),",
"      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Text(name, style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"        const SizedBox(height: 4),",
"        Text(type + ' - ' + location, style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"      ])),",
"    ]),",
"  );",
"}",
].join('\n'));

write('lib/screens/info/contact_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class ContactScreen extends StatelessWidget {",
"  const ContactScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Contact Support')),",
"      body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          Center(child: Icon(Icons.support_agent_outlined, size: 80, color: Colors.purple)),",
"          const SizedBox(height: 16),",
"          const Center(child: Text('We are here to help',",
"            style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"          const SizedBox(height: 8),",
"          Center(child: Text('Reach out to us through any of the channels below',",
"            textAlign: TextAlign.center,",
"            style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"          const SizedBox(height: 32),",
"          _ContactTile(icon: Icons.email_outlined, color: AppTheme.primary,",
"            title: 'Email Us', subtitle: 'mauzanimo@jcigrandbaie.mu'),",
"          const SizedBox(height: 12),",
"          _ContactTile(icon: Icons.phone_outlined, color: Colors.green,",
"            title: 'Call Us', subtitle: '+230 XXXX XXXX'),",
"          const SizedBox(height: 12),",
"          _ContactTile(icon: Icons.chat_outlined, color: Colors.blue,",
"            title: 'WhatsApp', subtitle: '+230 XXXX XXXX'),",
"          const SizedBox(height: 12),",
"          _ContactTile(icon: Icons.location_on_outlined, color: Colors.orange,",
"            title: 'Find Us', subtitle: 'Grand Baie, Mauritius'),",
"          const SizedBox(height: 32),",
"          const Text('Business Hours',",
"            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 12),",
"          Container(padding: const EdgeInsets.all(16),",
"            decoration: BoxDecoration(color: AppTheme.lightGrey, borderRadius: BorderRadius.circular(12)),",
"            child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"              Text('Monday - Friday: 9:00 AM - 5:00 PM', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"              SizedBox(height: 6),",
"              Text('Saturday: 9:00 AM - 12:00 PM', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"              SizedBox(height: 6),",
"              Text('Sunday: Closed', style: TextStyle(fontSize: 14, color: AppTheme.textDark)),",
"            ]),",
"          ),",
"        ],",
"      )),",
"    );",
"  }",
"}",
"",
"class _ContactTile extends StatelessWidget {",
"  final IconData icon; final Color color; final String title, subtitle;",
"  const _ContactTile({required this.icon, required this.color, required this.title, required this.subtitle});",
"  @override",
"  Widget build(BuildContext context) => Container(",
"    padding: const EdgeInsets.all(16),",
"    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
"      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 8, offset: const Offset(0, 2))]),",
"    child: Row(children: [",
"      Container(padding: const EdgeInsets.all(10),",
"        decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(10)),",
"        child: Icon(icon, color: color)),",
"      const SizedBox(width: 16),",
"      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Text(title, style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"        const SizedBox(height: 4),",
"        Text(subtitle, style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"      ])),",
"    ]),",
"  );",
"}",
].join('\n'));

write('lib/screens/info/about_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class AboutScreen extends StatelessWidget {",
"  const AboutScreen({super.key});",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('About MauZanimo')),",
"      body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          Center(child: Icon(Icons.pets, size: 80, color: AppTheme.primary)),",
"          const SizedBox(height: 16),",
"          const Center(child: Text('MauZanimo',",
"            style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"          const SizedBox(height: 8),",
"          Center(child: Text('Connecting stray pets with loving homes in Mauritius',",
"            textAlign: TextAlign.center,",
"            style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"          const SizedBox(height: 32),",
"          const Text('Our Mission',",
"            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 8),",
"          const Text('MauZanimo is a digital adoption platform built by JCI Grand Baie to connect stray pets with loving families across Mauritius. We believe every animal deserves a safe and caring home.',",
"            style: TextStyle(fontSize: 14, color: Colors.grey, height: 1.6)),",
"          const SizedBox(height: 24),",
"          const Text('Our Values',",
"            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"          const SizedBox(height: 12),",
"          _ValueTile(icon: Icons.favorite_outline, color: Colors.red, title: 'Compassion', description: 'Every animal matters'),",
"          const SizedBox(height: 8),",
"          _ValueTile(icon: Icons.verified_outlined, color: AppTheme.primary, title: 'Transparency', description: 'Open and honest adoption process'),",
"          const SizedBox(height: 8),",
"          _ValueTile(icon: Icons.groups_outlined, color: Colors.orange, title: 'Community', description: 'Building a kinder Mauritius together'),",
"          const SizedBox(height: 24),",
"          Container(padding: const EdgeInsets.all(16),",
"            decoration: BoxDecoration(color: AppTheme.primary.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),",
"            child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"              Text('Powered by JCI Grand Baie', style: TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"              SizedBox(height: 4),",
"              Text('Junior Chamber International Grand Baie is a youth-led organization dedicated to creating positive change in Mauritius.',",
"                style: TextStyle(fontSize: 12, color: Colors.grey, height: 1.5)),",
"            ]),",
"          ),",
"          const SizedBox(height: 16),",
"          Center(child: Text('Version 1.0.0', style: TextStyle(fontSize: 12, color: Colors.grey.shade400))),",
"        ],",
"      )),",
"    );",
"  }",
"}",
"",
"class _ValueTile extends StatelessWidget {",
"  final IconData icon; final Color color; final String title, description;",
"  const _ValueTile({required this.icon, required this.color, required this.title, required this.description});",
"  @override",
"  Widget build(BuildContext context) => Container(",
"    padding: const EdgeInsets.all(16),",
"    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
"      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 8, offset: const Offset(0, 2))]),",
"    child: Row(children: [",
"      Container(padding: const EdgeInsets.all(10),",
"        decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(10)),",
"        child: Icon(icon, color: color)),",
"      const SizedBox(width: 16),",
"      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
"        Text(title, style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"        const SizedBox(height: 4),",
"        Text(description, style: const TextStyle(fontSize: 12, color: Colors.grey)),",
"      ])),",
"    ]),",
"  );",
"}",
].join('\n'));

write('lib/screens/info/volunteer_screen.dart', [
"import 'package:flutter/material.dart';",
"import 'package:cloud_firestore/cloud_firestore.dart';",
"import 'package:firebase_auth/firebase_auth.dart';",
"import 'package:stray_pets_mu/theme/app_theme.dart';",
"",
"class VolunteerScreen extends StatefulWidget {",
"  const VolunteerScreen({super.key});",
"  @override",
"  State<VolunteerScreen> createState() => _VolunteerScreenState();",
"}",
"class _VolunteerScreenState extends State<VolunteerScreen> {",
"  final _nameController = TextEditingController();",
"  final _phoneController = TextEditingController();",
"  final _messageController = TextEditingController();",
"  bool _isLoading = false;",
"  bool _submitted = false;",
"",
"  Future<void> _submit() async {",
"    if (_nameController.text.isEmpty || _phoneController.text.isEmpty) {",
"      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill in all required fields')));",
"      return;",
"    }",
"    setState(() => _isLoading = true);",
"    try {",
"      await FirebaseFirestore.instance.collection('volunteers').add({",
"        'name': _nameController.text.trim(),",
"        'phone': _phoneController.text.trim(),",
"        'message': _messageController.text.trim(),",
"        'userId': FirebaseAuth.instance.currentUser?.uid,",
"        'email': FirebaseAuth.instance.currentUser?.email,",
"        'createdAt': FieldValue.serverTimestamp(),",
"      });",
"      setState(() => _submitted = true);",
"    } catch (e) {",
"      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Something went wrong.')));",
"    } finally {",
"      setState(() => _isLoading = false);",
"    }",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      appBar: AppBar(title: const Text('Volunteer')),",
"      body: _submitted ? _success() : _form(),",
"    );",
"  }",
"",
"  Widget _success() => Center(child: Padding(padding: const EdgeInsets.all(32), child: Column(",
"    mainAxisAlignment: MainAxisAlignment.center,",
"    children: [",
"      const Icon(Icons.check_circle_outline, size: 100, color: AppTheme.primary),",
"      const SizedBox(height: 24),",
"      const Text('Thank You!', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppTheme.textDark)),",
"      const SizedBox(height: 12),",
"      const Text('We have received your volunteer application. Our team will be in touch soon!',",
"        textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Colors.grey, height: 1.6)),",
"      const SizedBox(height: 32),",
"      ElevatedButton(onPressed: () => Navigator.pop(context), child: const Text('Go Back')),",
"    ])));",
"",
"  Widget _form() => SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(",
"    crossAxisAlignment: CrossAxisAlignment.start,",
"    children: [",
"      Center(child: Icon(Icons.volunteer_activism_outlined, size: 64, color: Colors.orange)),",
"      const SizedBox(height: 16),",
"      const Center(child: Text('Join Our Team', style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.textDark))),",
"      const SizedBox(height: 8),",
"      Center(child: Text('Help us make a difference for stray animals in Mauritius',",
"        textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: AppTheme.textDark.withOpacity(0.6)))),",
"      const SizedBox(height: 32),",
"      _f(_nameController, 'Full Name', Icons.person_outline),",
"      const SizedBox(height: 16),",
"      _f(_phoneController, 'Phone Number', Icons.phone_outlined, keyboardType: TextInputType.phone),",
"      const SizedBox(height: 16),",
"      _f(_messageController, 'How would you like to help?', Icons.message_outlined, maxLines: 4),",
"      const SizedBox(height: 32),",
"      SizedBox(width: double.infinity, child: ElevatedButton(",
"        onPressed: _isLoading ? null : _submit,",
"        child: _isLoading ? const CircularProgressIndicator(color: Colors.white) : const Text('Apply to Volunteer'))),",
"    ]));",
"",
"  Widget _f(TextEditingController c, String label, IconData icon,",
"    {TextInputType keyboardType = TextInputType.text, int maxLines = 1}) =>",
"    TextField(controller: c, keyboardType: keyboardType, maxLines: maxLines,",
"      decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon),",
"        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),",
"        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12),",
"          borderSide: const BorderSide(color: AppTheme.primary, width: 2))));",
"}",
].join('\n'));
